# Generated by Django 3.2.5 on 2021-11-18 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventos',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='event_date',
            field=models.DateTimeField(verbose_name='Data do Evento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
